### ISSUE TITLE
TypeError: (intermediate value).create is not a function

### ISSUE THREAD

**Issue by svendjanis** [atularen/ngx-monaco-editor#147]
TypeError: (intermediate value)(intermediate value)(intermediate value).create is not a function.

I am using it as a component and opening it in another component as a dialog.

**Comment by mistic100** [comment]
@svendjanis what was the issue ? can you tell how you solved it ?

**Comment by mistic100** [comment]
Answering my own question : in my case I initialized the editor with content from a file loaded with webpack raw-loader. After updates from raw-loader 1.0.0 to 3.0.0 the return value of the loader changed, it is now an object with a "default" property which is the file content.

**Comment by svendjanis** [comment]
It was my mistake, sorry. My initial value of the editor was wrong. It was an object instead of a string

**Comment by RITIKHARIANI** [comment]
Hey, I am getting the same error while running Karma unit tests
But I am not creating the editor anywhere. 
I just call `<ngx-monaco-editor>` with a few editor options in the html. 
Any idea on how I can fix this issue?
