### ISSUE TITLE
Command Pallete is not working with monaco > 0.44.0

### ISSUE THREAD

**Issue by jandeu** [atularen/ngx-monaco-editor#281]
After updating Monaco to a version newer than 0.44.0, the Command Palette stopped working.

## Reproduction Steps

1. Open the provided example page. [https://ngx-monaco-editor-v2.surge.sh](https://ngx-monaco-editor-v2.surge.sh/)
2. Press F1 to open the Command Palette in any editor.
3. The Command Palette opens, but no commands are available. The following error appears in the console:

```
Uncaught (in promise) TypeError: Y.reduce is not a function
    at q.setElements (quickInputTree.ts:1071:37)
    at quickInput.ts:1007:18
    at L.bufferEvents (event.ts:1585:13)
    at r.update (quickInput.ts:1006:29)
    at set items (quickInput.ts:629:8)
    at f (pickerQuickAccess.ts:194:12)
    at c (pickerQuickAccess.ts:300:5)
    at c.value (pickerQuickAccess.ts:324:49)
    at u._deliver (event.ts:1225:13)
    at u._deliverQueue (event.ts:1236:9)
```

## Additional Context

I found a similar issue reported in the Monaco repository, where it was suggested that the problem may be related to zone.js and promises:
[microsoft/monaco-editor/issues/4372](https://github.com/microsoft/monaco-editor/issues/4372)
